<!doctype html>
<html lang="uk">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Технічний довідник компонентів і станів інтерфейсу Dwelchain.">
  <meta name="robots" content="noindex">
  <title>Дизайн-система | Dwelchain</title>
  <link rel="icon" type="image/png" href="{{ asset('assets/images/dwelchain-mark.png') }}">
  <link rel="stylesheet" href="{{ asset('assets/css/styles.css') }}?v=20260725-accounts1">
</head>
<body data-page="design-system">
  <div data-site-header></div>
  <main class="design-system section-shell">
    <section class="design-system__intro"><p class="eyebrow"><span></span> Технічний довідник</p><h1>Дизайн-система Dwelchain</h1><p>Робоча сторінка компонентів і станів. Не входить до презентаційних макетів.</p></section>
    <section class="specimen"><div class="specimen__title"><span>01</span><h2>Кольори</h2></div><div class="swatches"><article class="swatch swatch--gold"><i></i><strong>Золотий</strong><code>#C9A45A</code></article><article class="swatch swatch--ink"><i></i><strong>Основний темний</strong><code>#1A1A1D</code></article><article class="swatch swatch--ink-two"><i></i><strong>Другорядний темний</strong><code>#2C2C31</code></article><article class="swatch swatch--line"><i></i><strong>Світло-сірий</strong><code>#D9D9D8</code></article><article class="swatch swatch--surface"><i></i><strong>Основний фон</strong><code>#F3F3F5</code></article></div></section>
    <section class="specimen"><div class="specimen__title"><span>02</span><h2>Типографіка</h2></div><div class="type-samples"><div><small>Великі заголовки · Montserrat 700</small><div class="type-display">Нерухомість<br>у Києві.</div></div><div><small>Основний текст · Open Sans 400</small><p>Висока читабельність, спокійний ритм і достатньо простору для інформації про об’єкти.</p></div></div></section>
    <section class="specimen"><div class="specimen__title"><span>03</span><h2>Кнопки та стани</h2></div><div class="component-row"><button class="button button--primary">Основна кнопка</button><button class="button button--secondary">Другорядна</button><button class="button button--text">Текстова дія</button><button class="button button--primary" disabled>Недоступна</button></div></section>
    <section class="specimen"><div class="specimen__title"><span>04</span><h2>Поля та фільтри</h2></div><div class="component-row component-row--fields"><label class="field"><span>Район</span><select><option>Печерський</option></select></label><label class="field"><span>Ціна від, $</span><input type="number" placeholder="150 000"></label><label class="field"><span>Площа від, м²</span><input type="number" placeholder="60"></label><label class="field"><span>Ремонт</span><select><option>Сучасний</option></select></label><label class="field"><span>Тип будинку</span><select><option>Монолітний</option></select></label><label class="field"><span>Коментар</span><textarea rows="2" placeholder="Короткий текст"></textarea></label><label class="checkbox-field"><input type="checkbox" checked><span>Погоджений параметр</span></label><fieldset class="radio-group"><legend>Тип угоди</legend><label><input type="radio" name="design-deal" checked><span>Купівля</span></label><label><input type="radio" name="design-deal"><span>Оренда</span></label></fieldset><span class="filter-chip">Купівля <button aria-label="Видалити фільтр: тип угоди — купівля">×</button></span><span class="badge">Нове оголошення</span><span class="badge badge--dark">Купівля</span></div></section>
    <section class="specimen"><div class="specimen__title"><span>05</span><h2>Картка об’єкта</h2></div><div class="property-grid property-grid--single" id="design-card"></div></section>
    <section class="specimen"><div class="specimen__title"><span>06</span><h2>Модальні вікна</h2></div><div class="component-row"><button class="button button--primary" data-modal-open="viewing-modal">Записатися на перегляд</button><button class="button button--secondary" data-modal-open="manager-modal">Зв’язатися з менеджером</button><button class="button button--secondary" data-modal-open="owner-modal">Запропонувати об’єкт</button></div></section>
    <section class="specimen"><div class="specimen__title"><span>07</span><h2>Breadcrumbs і форма</h2></div><div class="specimen-stack"><nav class="breadcrumbs breadcrumbs--compact" aria-label="Приклад навігаційного шляху"><a href="{{ url('/') }}">Головна</a><span>·</span><a href="{{ url('/catalog') }}">Каталог</a><span>·</span><span>Об’єкт</span></nav><form class="specimen-form"><label class="field"><span>Ім’я</span><input value="Олександр"></label><label class="field"><span>Телефон</span><input value="+380 00 000 00 00"></label><button class="button button--primary" type="button">Надіслати заявку</button></form></div></section>
    <section class="specimen"><div class="specimen__title"><span>08</span><h2>Карта-заглушка</h2></div><div class="specimen-stack"><div id="design-map"></div><div id="design-map-empty"></div><div class="map-components-specimen"><button class="map-marker map-marker--specimen is-active" type="button" aria-label="Активний маркер: 285 000 доларів"><span>285 000 $</span><i></i></button><article class="map-popup map-popup--specimen"><span class="map-popup__image"><img src="{{ asset('assets/images/living-room.png') }}" alt="Вітальня з панорамними вікнами"></span><div><small>Печерський · Купівля</small><h3>Квартира з панорамними вікнами</h3><strong>285 000 $</strong><a href="{{ url('/property') }}?id=pechersk-skyline">Переглянути об’єкт →</a></div></article></div></div></section>
    <section class="specimen"><div class="specimen__title"><span>09</span><h2>Інвестиційна картка</h2></div><aside class="investment-profile investment-profile--specimen"><div class="investment-profile__top"><span>Приклад первинної оцінки</span><b>Купівля</b></div><p>Квартира з панорамними вікнами на Печерську</p><strong>285 000 $</strong><div class="investment-profile__facts"><span><small>Площа</small><b>92 м²</b></span><span><small>Кімнати</small><b>3</b></span><span><small>Район</small><b>Печерський</b></span><span><small>Ціна за м²</small><b>3 098 $</b></span></div></aside></section>
    <section class="specimen"><div class="specimen__title"><span>10</span><h2>Операційна модель</h2></div><div class="business-model__grid business-model__grid--specimen"><article class="business-step"><i aria-hidden="true">✓</i><span>Крок 01</span><h3>Збір об’єктів спеціалістами</h3><p>Штатні колектори Dwelchain виїжджають до власника, оглядають нерухомість, збирають документи та вносять об’єкт у систему.</p></article><article class="business-step"><i aria-hidden="true">▣</i><span>Крок 02</span><h3>Фото- та відеозйомка</h3><p>Наш фотограф проводить професійну зйомку: широкоформатні фото, відеотур та планування приміщень для публікації на платформі.</p></article></div></section>
    <section class="specimen"><div class="specimen__title"><span>11</span><h2>CTA та footer</h2></div><div class="specimen-stack"><div class="compact-cta compact-cta--specimen"><div><p class="eyebrow eyebrow--gold"><span></span> Маєте нерухомість?</p><h3>Запропонуйте об’єкт для розміщення</h3></div><button class="button button--light" type="button" data-modal-open="owner-modal">Запропонувати об’єкт</button></div><div class="footer-components"><div><strong>Dwelchain</strong><span>Нерухомість для життя та інвестицій.</span></div><div><small>Контакти</small><a href="tel:+380441234567">+380 44 123 45 67</a><a href="mailto:hello@dwelchain.com">hello@dwelchain.com</a></div></div></div></section>
    <section class="specimen"><div class="specimen__title"><span>12</span><h2>Системні стани</h2></div><div class="state-grid"><article class="state-card"><strong>Loading</strong><div class="state-loading" aria-label="Завантаження"></div></article><article class="state-card"><strong>Empty</strong><p>За цими параметрами нічого не знайдено.</p><button class="button button--secondary" type="button">Очистити фільтри</button></article><article class="state-card state-card--error"><strong>Error</strong><p>Не вдалося завантажити об’єкти.</p><button class="button button--secondary" type="button">Спробувати ще раз</button></article><article class="state-card state-card--success"><strong>Success</strong><p>Форму заповнено. У цій версії прототипу дані не надсилаються.</p></article><article class="state-card state-card--notification"><strong>Notification</strong><p>Параметри пошуку застосовано.</p></article><article class="state-card"><strong>Fallback image</strong><span class="property-card__placeholder property-card__placeholder--specimen" aria-label="Фотографія об’єкта відсутня"><b>D</b><small>Фото ще не додано</small></span></article></div></section>
    <section class="specimen"><div class="specimen__title"><span>13</span><h2>Компоненти кабінету</h2></div><div class="account-components-specimen"><div class="account-role-switch"><a class="is-active" href="{{ url('/account') }}?role=tenant">Орендар</a><a href="{{ url('/account') }}?role=landlord">Орендодавець</a></div><nav class="account-nav" aria-label="Приклад навігації кабінету"><a class="is-active" href="{{ url('/account') }}?role=tenant"><span>◇</span>Огляд</a><a href="{{ url('/account') }}?role=tenant&amp;view=saved"><span>▦</span>Збережені об’єкти</a><a href="{{ url('/account') }}?role=tenant&amp;view=viewings"><span>□</span>Мої перегляди</a></nav><div class="account-components-specimen__states"><span class="account-status is-new">Нова заявка</span><span class="account-status is-pending">Потребує підтвердження</span><span class="account-status is-complete">Завершено</span><div class="prototype-notice"><b>Демонстраційний кабінет</b><span>Дані не зберігаються.</span></div></div></div></section>
  </main>
  <div data-site-footer></div>
  <script type="module" src="{{ asset('assets/js/app.js') }}?v=20260725-investors1"></script>
</body>
</html>
